name: DBCustomQueries Script Workflow

on:
  push:
    branches: ['main']
    paths: ['dbcustomqueries/**']

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
      
      - name: Run Python script
        env:
            CLIENT_ID: ${{ secrets.CLIENT_ID }}
            CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
            CONTROLLER_URL: ${{ secrets.CONTROLLER_URL }}
        run: |
          python -m pip install requests
          python appd_db_customsql.py
